# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  assets:
    name: Build and release assets
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: set the release version (tag)
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.86
          default: true
          components: clippy, rustfmt

      - name: Install Wasm Rust target
        run: rustup target add wasm32-wasip1

      - name: Make
        run: make
        env:
          RUST_LOG: spin=trace

      - name: generate checksums
        run: |
          sha256sum target/wasm32-wasip1/release/spin_static_fs.wasm > checksums-${{ env.RELEASE_VERSION }}.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/wasm32-wasip1/release/spin_static_fs.wasm
            checksums-${{ env.RELEASE_VERSION }}.txt
